# Basic Operations and Arrays

In [1]:
import numpy as np

## 1. Write a NumPy program to get help with the add function.

In [2]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

print(np.info(np.add)) prints information about the np.add function, which is a function in NumPy used for element-wise addition of two arrays. The np.info() function provides detailed information about a given NumPy function or class, including a description, input parameters, return values, and examples of usage.

## 2. Write a NumPy program to test whether none of the elements of a given array are zero. 

In [3]:
x = np.array([1,2,3,4])
print(x)
print(np.all(x))

x = np.array([1,0,2,3,4])
print(x)
print(np.all(x))

[1 2 3 4]
True
[1 0 2 3 4]
False


x = np.array([1, 2, 3, 4]): This line creates a NumPy array 'x' with the elements 1, 2, 3, and 4.

print(np.all(x)): This line uses the np.all() function to test if all elements in the array 'x' are non-zero (i.e., not equal to zero). In this case, all elements are non-zero, so the function returns True.

## 3. Write a NumPy program to test if any of the elements of a given array are non-zero. 

In [4]:
x = np.array([1,0,0,0])
print(x)
print(np.any(x))

x = np.array([0,0,0,0])
print(x)
print(np.any(x))

[1 0 0 0]
True
[0 0 0 0]
False


x = np.array([1, 0, 0, 0]): This line creates a NumPy array 'x' with the elements 1, 0, 0, and 0.

print(np.any(x)): This line uses the np.any() function to test if any elements in the array 'x' are non-zero (i.e., not equal to zero). In this case, the first element is non-zero, so the function returns True.

## 4. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [5]:
a = np.array([1,0,np.nan,np.inf])
print(a)
print(np.isfinite(a))

[ 1.  0. nan inf]
[ True  True False False]


## 5. Write a NumPy program to test elements-wise for positive or negative infinity. 

In [6]:
a = np.array([1,-2,np.inf,-np.inf,0,3.5])
print(a)
print("Element-wise positive infinity check:", np.isposinf(a))
print("Element-wise negative infinity check:", np.isneginf(a))

[ 1.  -2.   inf -inf  0.   3.5]
Element-wise positive infinity check: [False False  True False False False]
Element-wise negative infinity check: [False False False  True False False]


## 6. Write a NumPy program to test element-wise for NaN of a given array.

In [7]:
a = np.array([1,0,np.nan,np.inf])
print(a)
print(np.isnan(a))

[ 1.  0. nan inf]
[False False  True False]


## 7. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [8]:
a = np.zeros(10)
print(a)

b = np.ones(10)
print(b)

c = b * 5
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 8. Write a NumPy program to create an array of integers from 30 to 70.

In [9]:
a = np.arange(30,70)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


## 9. Write a NumPy program to create an array of all even integers from 30 to 70.

In [10]:
a = np.arange(30,70,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


## 10. Write a NumPy program to create a 3x3 identity matrix

In [11]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 11. Write a NumPy program to generate a random number between 0 and 1.

In [12]:
rand_num = np.random.normal(0,1,1)
print(rand_num)

[-2.48034026]


## 12. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [13]:
rand_num = np.random.normal(0,1,15)
print(rand_num)

[-0.53263557  1.49575388 -0.73484678 -0.26548357 -0.91495241  0.50387967
  0.50058525 -2.05360221 -0.01093998 -0.60474394  1.29108698  0.44183097
  1.69025125 -0.67277102 -0.29075862]


## 13. Write a NumPy program to create a 3X4 array and iterate over it.

In [14]:
a = np.arange(10,22).reshape((3,4))
a

for x in np.nditer(a):
    print(x, end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 

## 14. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [15]:
v = np.linspace(5, 50, 10)
print(v)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


## 15. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [16]:
x = np.arange(21)
print(x)

x[(x>=9)&(x<=15)] *= -1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


## 16. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [17]:
x = np.ones((10, 10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 17. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [18]:
y = np.diag([1,2,3,4,5])
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Statistics

## 1. Write a Python program to find the maximum and minimum value of a given flattened array.

In [19]:
x = np.arange(4).reshape((2, 2))
print(x)
print("Max:",np.max(x))
print("Min:",np.min(x))

[[0 1]
 [2 3]]
Max: 3
Min: 0


## 2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

In [20]:
x = np.arange(4).reshape((2, 2))
print(x)

print("Maximum Value")
print(np.amax(x, 1))
print("Minimum Value")
print(np.amin(x, 1)) 

[[0 1]
 [2 3]]
Maximum Value
[1 3]
Minimum Value
[0 2]


np.amax(x, 1): Here np.amax(x, 1) returns the maximum value along the 1st axis (rows) of x which is a 2x2 array. This returns a 1D array with 2 elements where each element is the maximum value of its corresponding row in the original x array. 

## 3. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.

In [21]:
x = np.arange(12).reshape((2, 6))
print(x)

res = np.amax(x, 1) - np.amin(x, 1) 
print(res)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[5 5]


## 4. Write a NumPy program to compute the median of flattened given array.

In [22]:
x = np.arange(12).reshape((2, 6))
print(x)
print("Median", np.median(x))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Median 5.5


## 5. Write a NumPy program to compute the weighted of a given array.

In [23]:
x = np.arange(5)
print(x)

# Creating weights from 1 to 5 using arange
weights = np.arange(1, 6)

print("Weighted Average", np.average(x, weights=weights))

[0 1 2 3 4]
Weighted Average 2.6666666666666665


weights = np.arange(1, 6): Here numpy.arange generates the values [1, 2, 3, 4, 5], which will be used as the weights for the weighted average calculation.

The numpy.average function is then used to calculate the weighted average of x using the weights array. 

## 6. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.

In [24]:
x = np.arange(6)
print(x)

print("Mean", np.mean(x))
print("Standard Deviation", np.std(x))
print("Variance", np.var(x))

[0 1 2 3 4 5]
Mean 2.5
Standard Deviation 1.707825127659933
Variance 2.9166666666666665


## 7. Write a NumPy program to compute the covariance matrix of two given arrays.

In [25]:
x = np.arange(3)
print(x)

y = np.array([2,1,0])
print(y)

print("Covariance:\n", np.cov(x,y))

[0 1 2]
[2 1 0]
Covariance:
 [[ 1. -1.]
 [-1.  1.]]


## 8. Write a NumPy program to compute cross-correlation of two given arrays.

In [26]:
x = np.array([0, 1, 3])
print(x)
y = np.array([2, 4, 5])
print(y)

print("Correlation:\n",np.correlate(x,y))

[0 1 3]
[2 4 5]
Correlation:
 [19]


# Random

## 1. Write a NumPy program to generate five random numbers from the normal distribution.

In [27]:
x = np.random.normal(size=5)
print(x)

[-0.21711141 -2.1231427  -0.35090937 -1.31791128  0.54102927]


## 2. Write a NumPy program to generate six random integers between 10 and 30.

In [28]:
x = np.random.randint(low=10, high=30, size=6)
print(x)

[22 20 12 15 23 21]


## 3. Write a NumPy program to create a 3x3x3 array with random values.

In [29]:
x = np.random.random((3,3,3))
print(x)

[[[0.36852629 0.81237374 0.89401279]
  [0.02958041 0.89753627 0.84019874]
  [0.76453837 0.75580942 0.66704028]]

 [[0.19393635 0.33359936 0.94641179]
  [0.63959598 0.76160504 0.82111878]
  [0.37567148 0.22286533 0.66377092]]

 [[0.11350962 0.38258377 0.23334424]
  [0.39759325 0.67271569 0.56371406]
  [0.75433192 0.49827311 0.69356806]]]


## 4. Write a NumPy program to shuffle numbers between 0 and 10.

In [30]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[0 9 7 5 2 4 1 3 8 6]


## 5. Write a NumPy program to normalize a 3x3 random matrix.

In [31]:
x = np.random.random((3, 3))
print(x)

xmax, xmin = x.max(), x.min()
x = (x - xmin) / (xmax - xmin)

print("After normalization:")
print(x) 

[[0.60589231 0.93963677 0.63298951]
 [0.56069232 0.14283165 0.23636276]
 [0.79767374 0.94327564 0.65709353]]
After normalization:
[[0.57850476 0.99545394 0.61235748]
 [0.52203611 0.         0.11684904]
 [0.81809858 1.         0.64247078]]


## 6. Write a NumPy program to check two random arrays are equal or not

In [33]:
x = np.random.randint(0, 2, 6)
print(x)
y = np.random.randint(0, 2, 6)
print(y)

array_equal = np.allclose(x, y)
print("Test above two arrays are equal or not!")
print(array_equal) 

[1 1 0 0 0 1]
[1 1 0 1 0 1]
Test above two arrays are equal or not!
False
