In [2]:
import numpy as np

# 1. Get the numpy version and show numpy build configuration

In [3]:
print(np.__version__)

1.26.4


In [4]:
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/Anaconda3/Library/include
    lib directory: C:/ProgramData/Anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2252572576928
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

# 2. Test whether none of the elements of a given array is zero

In [7]:
a = np.array([1,2,3,4])
b = np.array([0,1,2,3])

print(np.all(a))
print(np.all(b))

True
False


# 3. Create array with all zeros 

In [8]:
a = np.zeros([3,4],dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 4. Create a Numpy array filled with all ones

In [9]:
a = np.ones([3,4],dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 5. Check whether a Numpy array contains a specified row

In [10]:
arr = np.array([[1, 2, 3, 4, 5], 
                   [6, 7, 8, 9, 10], 
                   [11, 12, 13, 14, 15], 
                   [16, 17, 18, 19, 20] 
                   ])

print([1,2,3,4,5] in arr.tolist())
print([16,17,20,19,18]   in arr.tolist())
print([3,2,5,-4,5]  in arr.tolist())
print([11,12,13,14,15]  in arr.tolist())

True
False
False
True


# 6. How to Remove rows in Numpy array that contains non-numeric values?

In [11]:
n_arr = np.array([[10.5, 22.5, 3.8, 5],
                  [23.45, 50, 78.7, 3.5],
                  [41, np.nan, np.nan, 0],
                  [20, 50.20, np.nan, 2.5],
                  [18.8, 50.60, 8.8, 58.6]])
n_arr

array([[10.5 , 22.5 ,  3.8 ,  5.  ],
       [23.45, 50.  , 78.7 ,  3.5 ],
       [41.  ,   nan,   nan,  0.  ],
       [20.  , 50.2 ,   nan,  2.5 ],
       [18.8 , 50.6 ,  8.8 , 58.6 ]])

In [14]:
clean_arr = n_arr[~np.isnan(n_arr).any(axis=1)]
clean_arr

array([[10.5 , 22.5 ,  3.8 ,  5.  ],
       [23.45, 50.  , 78.7 ,  3.5 ],
       [18.8 , 50.6 ,  8.8 , 58.6 ]])

# 7. Find the number of occurrences of a sequence in a NumPy array

In [16]:
arr = np.array([[2, 8, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 5, 9, 7], 
                   [2, 9, 4, 3]]) 

op = repr(arr).count("9, 4")
op

4

# 8. Find the most frequent value in a NumPy array

In [17]:
ar = np.array([1,2,3,4,5,1,2,1,1,1])
print(np.bincount(ar).argmax())

1


# 9. Combining a one and a two-dimensional NumPy Array

In [18]:
num_1d = np.arange(5) 
print(num_1d) 
  
num_2d = np.arange(10).reshape(2,5) 
print(num_2d)

for a, b in np.nditer([num_1d, num_2d]):
    print(a,b)

[0 1 2 3 4]
[[0 1 2 3 4]
 [5 6 7 8 9]]
0 0
1 1
2 2
3 3
4 4
0 5
1 6
2 7
3 8
4 9


# 10. Test a given array element-wise for finiteness (not infinity or not a Number)

In [19]:
a = np.array([1, 0, np.nan, np.inf])
a

array([ 1.,  0., nan, inf])

In [20]:
print(np.isfinite(a)) 

[ True  True False False]


# 11. Test element-wise for positive or negative infinity.

In [38]:
a = np.array([1, -2, np.inf, -np.inf, 0, 3.5])
print(np.isposinf(a))
print(np.isneginf(a))

[False False  True False False False]
[False False False  True False False]


# 12. Test element-wise for NaN of a given array

In [40]:
a = np.array([1, 0, np.nan, np.inf])
print(np.isnan(a))

[False False  True False]


# 13. Test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not

In [45]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

[ True False False False False  True]
[False  True  True  True  True False]
True
False


# 14. Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [48]:
x = np.array([3, 5])
y = np.array([2, 5])

print(np.greater(x, y))
print(np.greater_equal(x, y))
print(np.less(x, y))
print(np.less_equal(x, y))

[ True False]
[ True  True]
[False False]
[False  True]


# 15. create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [49]:
X = np.array([1, 7, 13, 105])
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize)) 

Size of the memory occupied by the said array:
16 bytes


# 16. create an array of 10 zeros, 10 ones, and 10 fives. 

In [1]:
x = np.zeros(10, dtype="int")
y = np.ones(10, dtype="int")
z = y*5

print(x)
print(y)
print(z)

NameError: name 'np' is not defined

# 17. Create a 3X4 array using and iterate over it

In [53]:
a = np.arange(10,22).reshape(3,4)

for x in np.nditer(a):
    print(x, end=",")

10,11,12,13,14,15,16,17,18,19,20,21,

# 18. Create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 19. Create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [64]:
x = np.ones((10, 10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 20. Create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [65]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 21. Create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [69]:
x = np.zeros((4, 4))

x[::2, 1::2] = 1
x[1::2,::2]=1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

# 22. Create a 3x3x3 array filled with arbitrary values

In [71]:
np.random.random((3,3,3))

array([[[0.24977524, 0.97402511, 0.85423427],
        [0.78542046, 0.24645405, 0.10399454],
        [0.20476848, 0.30826926, 0.17947582]],

       [[0.40041915, 0.2385701 , 0.9261291 ],
        [0.73232886, 0.83764063, 0.45863856],
        [0.08318278, 0.09903505, 0.88332356]],

       [[0.79693757, 0.38369762, 0.71318365],
        [0.43538957, 0.26012903, 0.14896073],
        [0.51663048, 0.4397267 , 0.12569563]]])

# 23. Compute sum of all elements, sum of each column and sum of each row of a given array

In [72]:
x = np.array([[0, 1, 3], [2, 3, 4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

13
[2 4 7]
[4 9]


# 24. Compute the inner product of two given vectors

In [73]:
x = np.array([4,5])
y = np.array([7,10])
print(np.dot(x, y))

78


# 25. Add a vector to each row of a given matrix

In [87]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# vector
v = np.array([1,1,0])

result = np.empty_like(m)

for i in range(4):
    result[i, :] = m[i, :] + v

In [89]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
result

array([[ 2,  3,  3],
       [ 5,  6,  6],
       [ 8,  9,  9],
       [11, 12, 12]])